### ISSUE TITLE
Query OSM solar panel locations

### ISSUE THREAD

**Issue by typicalTYLER** [typicalTYLER/SolarPanelDataWrangler#2]
Query OSM existing solar panel locations and persist for excluding locations from search/human verification

**Comment by typicalTYLER** [comment]
(This comment is mostly for rubber ducky debugging for me)

It looks like [overpy](https://github.com/DinoTools/python-overpy) is the best bet for querying this data directly. [overpassify](https://github.com/gappleto97/overpassify/) is another option, but is missing some functionality that might be useful to us. (But has nicer syntax)

With overpy I'm having a bit of trouble running the query showed [here](http://overpass-turbo.eu/s/HsX).

```
    api = overpy.Overpass()
    result = api.query(
        """[out:json][timeout:2500];
        {{geocodeArea:California}}->.searchArea;
        (
        node["generator:source"="solar"](area.searchArea);
        way["generator:source"="solar"](area.searchArea);
        );""")
```

This returns the error:
```
Traceback (most recent call last):
  File "/snap/pycharm-community/121/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/snap/pycharm-community/121/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-community/121/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/121/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/tyler/PycharmProjects/SolarPanelDataWrangler/solardb.py", line 153, in <module>
    query_osm_solar()
  File "/home/tyler/PycharmProjects/SolarPanelDataWrangler/solardb.py", line 148, in query_osm_solar
    );""")
  File "/home/tyler/PycharmProjects/SolarPanelDataWrangler/venv/lib/python3.5/site-packages/overpy/__init__.py", line 119, in query
    msgs=msgs
overpy.exception.OverpassBadRequest: Error: line 2: parse error: Unknown type "{" 
Error: line 2: parse error: An empty query is not allowed 
Error: line 2: parse error: ';' expected - '{' found. 
```

I'm thinking maybe the {{geocodeArea:[area]}} statement isn't allowed. Maybe overpass-turbo is a different language? Or embeds geocoding features.

**Comment by typicalTYLER** [comment]
Looks like overpass turbo has an extended set of instructions available to it (which aren't available in python) so I may have to re-implement them to some degree. https://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Turbo_Queries

**Comment by typicalTYLER** [comment]
This functionality added in 03be5b45a6a90eb4a8e64e84a726c241f49898da. For the time being the coordinates are stored in a simple table that just holds lat and lon.
